import Head from 'next/head';
import Sidebar from '../components/sidebar';

export default function Home() {
  return (
    <div className="bg-black h-screen overflow-hidden">
      <Head>
        <title>spotify-clone-apps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* First Developing */}
      <main className="">
        {/* Sidebar */}
        <Sidebar />
        {/* Center */}
      </main>
      
        <div>{/* Player */}</div>

    </div>     
  )
}